### ISSUE TITLE
Testlink import return 404

### ISSUE THREAD

**Issue by shawndibble** [msjit/testcasedb#102]
I have followed the instruction in the guide to set config.testlink_allowed to true. I also set the db settings. After that, I executed the url/install/testlink however I get a 404 error. I checked the routes, and there is no reference to install nor testlink.

App 32232 stdout: Started GET "/install/testlink" for 192.168.1.58 at 2015-08-28 16:25:13 -0500
App 32232 stdout:
App 32232 stdout: ActionController::RoutingError (No route matches [GET] "/install/testlink"):

**Comment by joffems** [comment]
@shawndibble The issue is in the code. I'm trying to pinpoint when this was introduced.
