### ISSUE TITLE
[Feature Request] Redis for caching

### ISSUE THREAD

**Issue by kirantpatil** [msjit/testcasedb#12]
Allow Redis as cache for testcasedb

**Comment by joffems** [comment]
@kirantpatil The code for this has been committed.

I'll be writing up instructions in the few days. Notice that if you don't make any config changes, the feature will simply be ignored.

**Comment by joffems** [comment]
@kirantpatil There are instructions in the README file explaining how to enable Redis.

**Comment by joffems** [comment]
Redis has been added to the admin guide.

Closing.
