### ISSUE TITLE
Intergrating Github Issues to Ticket System

### ISSUE THREAD

**Issue by nagarajpg** [msjit/testcasedb#49]
Hi All,
I want to add Github issue to Ticket System, So that user can raise issue after excuting a testcase. 
1) Add Github to config/en.yml
2) Use Github Api Gem to connect with Github ( http://peter-murach.github.com/github )

Am I going in the right way? Please reply. 

Thank you.

**Comment by kirantpatil** [comment]
any updates on this ?

**Comment by kirantpatil** [comment]
Hi Nagaraj,

I think it is better to have a issue tracker in the TCDB itself. 

I have raised an RFC for that, so please let me know what do you think.

If you agree then let me know so that we can tackle it together.

**Comment by kirantpatil** [comment]
https://github.com/msjit/testcasedb/issues/76
