### ISSUE TITLE
[Performance] ruby-prof-flamegraph support

### ISSUE THREAD

**Issue by kiranfractal** [msjit/testcasedb#63]
Hi,

I found this gem "gem 'ruby-prof-flamegraph'" at https://github.com/oozou/ruby-prof-flamegraph which may help us to detect performance issues.

Thanks.

**Comment by joffems** [comment]
@kiranfractal Are you seeing perfromance issues? This is definitely a worth while task, but it may be useful to leave this until there are complaints and/or a new UI.

Closing for now.

**Comment by kiranfractal** [comment]
I have not seen any issues so far.

I agree with you and we can take it up later.

Thanks.
