### ISSUE TITLE
404 page while accessing the webapi using json format

### ISSUE THREAD

**Issue by kiranfractal** [msjit/testcasedb#64]
Hi,

I am trying to check the webapi with json as below and it is giving me 404 error.

##### cat command.json :
-----------
{
  "api_request": {
    "command": "CheckVersion",
    "option1": "dummy1",
    "value": "1.2.3",
    "api_key": "oMPIgICN9KXsDhGgxfh"
  }
}

### curl -k --data-ascii @command.json https://178.79.180.79/versions /search.json?api_key=oMPIgICN9KXsDhGgxfh
----
<!DOCTYPE html>
<html>
<head>
  <title>TestCaseDB - (404)</title>
  <style type="text/css">
  body#login-page { background-color:#ffffff; margin-left: 0; margin-right: auto; text-align: left;}
  #login-container {height: 100%; overflow: hidden; position: relative; }
  #login-container[id] {display: table; position: static; }
  #login-middle {position: absolute; top: 35%; } /* for explorer only*/
  #login-middle[id] {display: table-cell; vertical-align: middle; width: 100%;}
  #login {top: -65%; position:relative; border: 2px solid #888888; width: 550px; margin-left: auto; margin-right: auto; background-color: #eeeeee; text-align: center; -moz-border-radius: 10px; border-radius: 10px;}
  #login h1 {font-size: 1.2em; color: #ff0000;}
  #login-footer { width:100%; background: #ffffff; font-size: 0.8em; color: #000000; padding: 7px 0px 7px 0px; text-align: center;  position:absolute;}
  .login-item { padding: 5px; width: 400px; margin-left: auto; margin-right: auto; text-align: left; }
  </style>
</head>

<body id="login-page">
	<div id="login-container">
  <div id="login-middle">
  <div id="login">
    <h1>The page you requested cannot be found.</h1>
    <div class="login-item">
      <p>
        If you continue to experience issues with this page, please contact your system administrator.
      </p>
    </div>
  </div>
  <div id="login-footer">Copyright &copy; 2012 MSJ IT Services. All rights reserved.</div>	
  </div>
  </div>
</body>
</html>

**Comment by agramian** [comment]
This is intended behavior. You do not want the test only items available in the production environment.  

You need to start the rails server in development or test mode and make sure the test/development environment and databases have been properly set up.

I believe to run in development or test mode you must run the setup script without the -p flag to create the databases and then for the gems run the rake command with the proper RAILS_ENV.
```
script/setup
rake assets:precompile RAILS_ENV=development
```
You may also have to restart the rails server.
```
passenger start -a 0.0.0.0 -p 3000 -d -e development
```
Something different may have to be done now with the updated version of rails but I'm not sure.

**Comment by kirantpatil** [comment]
@joffems, can we have a simple automation script using v2 webapi ?

**Comment by agramian** [comment]
@kirantpatil can you be more specific? What language and what are you trying to do? The v2 API provides very detailed error messages. Are you not able to even send and receive a request? You van even test it with a GUI tool like API kitchen.

**Comment by kirantpatil** [comment]
@agramian, I need a simple script to as shown in http://news.testcasedb.com/wp-content/uploads/2012/05/automation_example1.pdf  for testing GUI. I have no idea of how to access them and come up with a automated script.

I will check with API kitchen.

Thanks.

**Comment by kirantpatil** [comment]
I would like to use ruby to automate.

**Comment by agramian** [comment]
First of all @kirantpatil let's go back to your first example.

If you look at https://github.com/msjit/testcasedb/blob/master/spec/webapi/versions_api_spec.rb you will find example usage of the versions endpoint.

Your code should be revised as follows and it should work.

contents of command.json:
```
{
"version": "1.2.3",
"api_key": "oMPIgICN9KXsDhGgxfh"
}
```
curl command to TestCaseDB v2 web api
```
curl -k --data-ascii @command.json https://178.79.180.79/api/versions/search.json
```

**Comment by kiranfractal** [comment]
@agramian, yes now it worked. Thanks a lot.
