### ISSUE TITLE
User webapi is unnecessary

### ISSUE THREAD

**Issue by kirantpatil** [msjit/testcasedb#65]
In reality we don't see a separate user for automation purpose.

So, IMHO it is better to remove webapi user and allow by default QA manager, Senior Tester and Tester to act as webapi user.

Thanks.

**Comment by kiranfractal** [comment]
Any thoughts on this change ?

**Comment by joffems** [comment]
I prefer having a separate user for tracking and auditing purposes.

**Comment by kirantpatil** [comment]
How about combining roles ?

Ex: Tester + Webapi user, Senior Tester + Webapi User

That way we will have more granularity for user roles.

**Comment by joffems** [comment]
I don't have a problem with assigning multiple roles to a user, but that is a lower priority task.

I'm still not sure what the major issue is that we're trying to address here. Why do you want automated script tasks to be run by users?

**Comment by kirantpatil** [comment]
In product companies a person who is testing a module has to automate the same. He is the owner for both manual testing and automation.

With this combining roles we will have most flexibility and satisfies the requirement for different people needs.

**Comment by kirantpatil** [comment]
Closing this for now and feel free to reopen if it make sense.
