### ISSUE TITLE
Unable to save attachement

### ISSUE THREAD

**Issue by kirantpatil** [msjit/testcasedb#70]
Hi,

I did below steps to update the app
1) git pull 
2) rake db:migrate RAILS_ENV=production 
3) rake assets:precompile RAILS_ENV=production

I went to Result screen of one of the executed testcase and tried to upload a screenshot which is giving me below error.

It is expecting to install ImageMagick, is that correct ?

![screenshot from 2015-02-03 22 28 24](https://cloud.githubusercontent.com/assets/1178055/6024836/20488112-abf4-11e4-9620-99ba9cad9067.png)

Thanks.

**Comment by joffems** [comment]
ImageMagick is a system requirement for running TestCaseDB. the system uses ImageMagick to resize and alter images for previews. The install is included in the documentation. Installing imagemagick is pretty simple on ubuntu.

```
sudo apt-get install imagemagick
```

**Comment by kirantpatil** [comment]
Now with imagemagick installed it uploads but does not display the image, as shown in below screenshot.

Also we should get some pop up message as upload completed and blue loading bar should not display anymore.


![screenshot from 2015-02-04 21 49 55](https://cloud.githubusercontent.com/assets/1178055/6044195/d11b25f8-acb7-11e4-89de-a2216590ec5c.png)

**Comment by joffems** [comment]
Assuming things are working, the image should appear as  soon as the upload is complete. I'm assuming that the conversion failed. 

Can you please provide logs from the image upload.

Also, I will change the progress bar to disappear when the upload is complete.

**Comment by kirantpatil** [comment]
What logs should I provide ?

production.log or unicorn or any other ?

**Comment by joffems** [comment]
If you're running the production environment, production.log would be useful.

**Comment by kirantpatil** [comment]
Please find the attached production.log file.

**Comment by joffems** [comment]
@kirantpatil Can you please email the log to me. mjoffe _AT_ msjit.ca

**Comment by joffems** [comment]
The issue is with file types. The change I made is not working for non-image files. I simply need to set an icon for other file types. I will fix in the morning

**Comment by kirantpatil** [comment]
I upgraded to latest master and made changes for nginx in production.rb file and restarted the app and nginx and tried to upload a image and the blue bar still does not disappear once upload is finished.

![screenshot from 2015-02-07 07 58 39](https://cloud.githubusercontent.com/assets/1178055/6090433/28848846-ae9f-11e4-9017-324ee83194bf.png)

**Comment by joffems** [comment]
@kirantpatil A fix for the progress bars has been pushed.

**Comment by kirantpatil** [comment]
I updated the code and recompiled assets and reloaded unicorn and nginx and issue still persists.

![screenshot from 2015-02-07 20 44 30](https://cloud.githubusercontent.com/assets/1178055/6092558/6fd4134a-af0a-11e4-88ef-09a664f81d9e.png)

**Comment by joffems** [comment]
@kirantpatil Did you force a refresh in your browser? I currently can't reproduce this with the latest code in master.

Also, can you please let me know which browser you're seeing this issue with.

Thanks,
Marc

**Comment by kirantpatil** [comment]
I think I missed the nginx configuration file correction part. Looking in to it.

I added below code to nginx conf file, I am getting "404 Not Found" page for it.

I am getting below error.

testcasedb$ tail -f log/unicorn.stderr.log 
X-Accel-Mapping header missing
X-Accel-Mapping header missing
X-Accel-Mapping header missing
X-Accel-Mapping header missing
X-Accel-Mapping header missing
X-Accel-Mapping header missing
X-Accel-Mapping header missing
X-Accel-Mapping header missing
X-Accel-Mapping header missing
X-Accel-Mapping header missing

**Comment by kirantpatil** [comment]
I reverted all changes of nginx conf file and with only change in production.rb file image upload, delete works fine but I have no idea why the blue bar is not disappearing.

**Comment by kirantpatil** [comment]
I did "sudo ldconfig /usr/local/lib" as mentioned in http://robmclarty.com/blog/how-to-install-image-magick-and-setup-paperclip and restarted unicorn and nginx and it works now...
