### ISSUE TITLE
[RFC] issue management system for TCDB

### ISSUE THREAD

**Issue by kirantpatil** [msjit/testcasedb#76]
Hi,

I would like to know your opinion of having issue management as part of TCDB.

It is really difficult to maintain one project issue in Github and another in bugzilla and another in Gitorious and so on.

It make much sense to have a issue management system in TCDB and that way we need not worry of sending issues to different systems.

Note: Bugzilla has testopia as testcase management system.
https://developer.mozilla.org/en-US/docs/Mozilla/Bugzilla/Testopia

Thanks.

**Comment by kirantpatil** [comment]
I will work on this and will report the progress. But keep pouring your the suggestions. Goal is to keep it simple and usable.

**Comment by joffems** [comment]
Personally, I don't want to tackle this project right now. There are many great ticketing systems out there that companies have been using for a long time. That said, I'd be happy to accept work for this part of the project if you're willing to tackle it.

**Comment by kirantpatil** [comment]
Sure, I will tackle it. Even at first I was not in opinion of having it. But now it is making more and more sense to me to have it.

**Comment by kiranfractal** [comment]
I will use rails engine with the current Rails 3.2.21. So that I will get first hand experience of using engines and later can be ported to Rails 4.2.

**Comment by kirantpatil** [comment]
closing this for now, since I am planning to use other issue management solutions.
