### ISSUE TITLE
[Bug] Stencils show page fails to render if stencil has no description

### ISSUE THREAD

**Issue by agramian** [msjit/testcasedb#78]
If no description is entered for a stencil (description is NULL in the database), the view fails to render with the following error.
```
undefined method `truncate' for nil:NilClass
```
The truncate method shouldn't be called unless a string is present, or the default value for the description field should be an empty string.

**Comment by joffems** [comment]
@agramian Fix has been pushed. Never noticed this before as the form normally records an empty string as the value.Out of interest, did you create the test plan via the API?

**Comment by agramian** [comment]
@joffems yes i created via the API

**Comment by joffems** [comment]
This can definitely occur on other pages. I'm going to have to do a search for .truncate(  and then fix all the possible NPE exceptions.

**Comment by joffems** [comment]
@agramian I went digging through the code and I don't believe that this issue should occur anywhere else. Closing for now. Please re-open if you hit another issue.
