### ISSUE TITLE
500 error on refreshing the logout url

### ISSUE THREAD

**Issue by kirantpatil** [msjit/testcasedb#84]
Steps to reproduce:
-----------------------
1) login to tcdb using any username/password
2) logout of tcdb
3) refresh the browser

Expected output:
--------------------
Logout should not display in URL once tcdb is logged out

Actaual output:
------------------
After logout the URL displays the logout in the URL
or
After refresh the logout should no longer appear in the URL

Error message on browser:
---------------------------------
![screenshot from 2015-02-28 18 03 56](https://cloud.githubusercontent.com/assets/1178055/6426184/31eb0a46-bf74-11e4-92a8-f049d832fca7.png)

**Comment by joffems** [comment]
@kirantpatil A fix has been pushed.

**Comment by kirantpatil** [comment]
the bug has been verified and resolved.
