### ISSUE TITLE
how to change result?

### ISSUE THREAD

**Issue by nonovaliant** [msjit/testcasedb#87]
after i execute the case and save it , or jump the case to do the next. the result of case can't be changed or reset it.
![screenshot from 2015-03-11 16 40 17](https://cloud.githubusercontent.com/assets/11347581/6592847/8814d586-c80d-11e4-8e44-1c70364f91a8.png)
![screenshot from 2015-03-11 16 40 41](https://cloud.githubusercontent.com/assets/11347581/6592852/8de02bdc-c80d-11e4-81c9-aa8dbb83cd2e.png)

**Comment by joffems** [comment]
@nonovaliant There is a setting that can be enabled that allows users to change the result of a test case after it has already been set.

Open Admin -> Settings and enable "Low quality chocolate. Oddly, the insects were not the disgusting part! Not worth it."
